spring:
  datasource:
    url: default
    username: default
    password: default

  jdbc:
    initialize-schema: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect