spring:
  datasource:
    url: default
    username: default
    password: default

  batch:
    jdbc:
      initialize-schema: never
      table-prefix: batch.BATCH_

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  quarter: default
  year: default
  executor: default
  benchmark:
    regex: "\\s*\\(reflects no deduction for [^)]*\\)"